name: Build artifacts
on:
  workflow_call:

jobs:
  build:
    name: Build artifacts job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.OS }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-
      - name: Build artifacts
        env:
          REPO_SAYAN_USER: ${{ secrets.REPO_SAYAN_USER }}
          REPO_SAYAN_TOKEN: ${{ secrets.REPO_SAYAN_TOKEN }}
        run: ./gradlew build
