name: Publish Releases

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Generate NMS Components
        run: ./gradlew generateNmsComponents
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.OS }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Publish to Hangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          HANGAR_BUILD_CHANNEL: Release
          HANGAR_CHANGELOG: ${{ github.event.release.body }}
        run: ./gradlew build publishPluginPublicationToHangar --stacktrace
      - name: Publish to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_BUILD_CHANNEL: release
          MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}
          MODRINTH_CHANGELOG: ${{ github.event.release.body }}
      - name: Get artifact version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Attach artifact to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/VelocityVanish_${{ env.VERSION }}.jar
          asset_name: VelocityVanish_${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
