name: Publish Snapshots
on:
  push:
    branches:
      - master

jobs:
  build:
    uses: syrent/sayanvanish/.github/workflows/build-artifacts.yml@master
  publish_to_sayanrepo:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Publish to SayanDevelopment snapshot repo
        run: ./gradlew publish
        env:
          REPO_SAYAN_USER: ${{ secrets.REPO_SAYAN_USER }}
          REPO_SAYAN_TOKEN: ${{ secrets.REPO_SAYAN_TOKEN }}
