name: Publish Snapshots
on:
  workflow_run:
    workflows: ["Build artifacts"]
    types:
      - completed

jobs:
  publish_to_sayanrepo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Publish to SayanDevelopment snapshot repo
        run: ./gradlew publish
        env:
          REPO_SAYAN_USER: ${{ secrets.REPO_SAYAN_USER }}
          REPO_SAYAN_TOKEN: ${{ secrets.REPO_SAYAN_TOKEN }}
