name: Publish Snapshots
on:
  push:
    branches:
      - master

jobs:
  publish_to_sayanrepo:
    runs-on: ubuntu-22.04
    steps:
      - name: Call Build artifacts workflow
        uses: boi-carti/sayanvanish/.github/workflows/build-artifacts.yml@master
      - name: Publish to SayanDevelopment snapshot repo
        run: ./gradlew publish
        env:
          REPO_SAYAN_USER: ${{ secrets.REPO_SAYAN_USER }}
          REPO_SAYAN_TOKEN: ${{ secrets.REPO_SAYAN_TOKEN }}
