name: Publish modrinth
on:
  push:
    branches:
      - master

jobs:
  build:
    uses: syrent/sayanvanish/.github/workflows/build-artifacts.yml@master
  publish_to_modrinth:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Publish to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_BUILD_CHANNEL: beta
          MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}
          MODRINTH_CHANGELOG: ${{ github.event.release.body }}
